[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "my-rustfmt" }

[[language]]
name = "c"
indent = { tab-width = 2, unit = "  " }
auto-format = false

[[language]]
name = "cpp"
indent = { tab-width = 2, unit = "  " }
auto-format = false

[[language]]
name = "python"
indent = { tab-width = 2, unit = "  " }
auto-format = false

