#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         36

xss-lock -- xscreensaver-command -lock &

