[general]
grid_resize = true
vertical_split_handle_sticky = [33, 50, 67]
horizontal_split_handle_sticky = [33, 50, 67]
minimum_split_size_percent = 20

[layout]
workspaces = 4
gaps = 5
pad = [46, 10, 10, 10]
secondary_pad = [10, 10, 10, 10]

[window]
border = 4
title_font = "SF Pro Text 16"
title_bar_height = "+4"
right_buttons = ["close"]
icon_size = 90

[theme]
colors = "default"
icons = "Papirus"

[keys]
mod = "Win"

[keys.bindings]
'Mod+Q' = "close_window"
'Mod+Shift+Q' = "quit"
'Mod+space' = "$ launcher"
'Mod+Return' = "$ xfce4-terminal"
'Mod+Up' = "snap_maximized"
'Mod+Down' = "unsnap_or_center"
'Mod+Left' = "snap_left"
'Mod+Right' = "snap_right"
'Mod+Alt+Up' = "snap_up"
'Mod+Alt+Down' = "snap_down"
'Mod+Shift+Left' = "move_to_prev_monitor"
'Mod+Shift+Right' = "move_to_next_monitor"
# ^ Can't grab this for some reason?
'Mod+Ctrl+Left' = "move_to_prev_monitor"
'Mod+Ctrl+Right' = "move_to_next_monitor"
'Mod+Print' = "$ scrot ~/Pictures/Screenshots/%Y-%m-%d-%H%M%S-screenshot.jpg"
'XF86AudioLowerVolume' = "decrease_volume"
'XF86AudioRaiseVolume' = "increase_volume"
'XF86AudioMute' = "mute_volume"

[bar]
font = "SF Pro Text 18"
opacity = 80
height = "36"

[dock]
pinned = [
  "xfce4-terminal",
  "speedcrunch",
  "thunar",
  "chromium",
  "spotify-qt",
  "visual-studio-code"
]
